# Generated by Django 5.2.4 on 2025-07-31 06:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('inspection_by', models.CharField(max_length=100)),
                ('inspection_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SAVED', max_length=20)),
                ('bogie_details', models.JSONField(default=dict)),
                ('bogie_checksheet', models.JSONField(default=dict)),
                ('bmbc_checksheet', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bogie Checksheet',
                'verbose_name_plural': 'Bogie Checksheets',
                'db_table': 'bogie_checksheets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(db_index=True, help_text='Unique form identifier', max_length=50, unique=True)),
                ('submitted_by', models.CharField(help_text='User who submitted the form', max_length=100)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when form was submitted')),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SAVED', help_text='Current status of the form', max_length=20)),
                ('fields', models.JSONField(default=dict, help_text='Wheel specification data in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wheel Specification',
                'verbose_name_plural': 'Wheel Specifications',
                'db_table': 'wheel_specifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
