# Generated by Django 5.2.4 on 2025-07-31 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bogiechecksheet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='wheelspecification',
            options={},
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='form_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='form_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='status',
            field=models.CharField(choices=[('SAVED', 'Saved'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SAVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='submitted_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='bogiechecksheet',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wheelspecification',
            table=None,
        ),
    ]
