# Generated by Django 5.2.4 on 2025-07-31 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_bogiechecksheet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bogiechecksheet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bogie Checksheet', 'verbose_name_plural': 'Bogie Checksheets'},
        ),
        migrations.AlterModelOptions(
            name='wheelspecification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wheel Specification', 'verbose_name_plural': 'Wheel Specifications'},
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='form_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='fields',
            field=models.JSONField(default=dict, help_text='Wheel specification data in JSON format'),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='form_number',
            field=models.CharField(db_index=True, help_text='Unique form identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='status',
            field=models.CharField(choices=[('SAVED', 'Saved'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SAVED', help_text='Current status of the form', max_length=20),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='submitted_by',
            field=models.CharField(help_text='User who submitted the form', max_length=100),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when form was submitted'),
        ),
        migrations.AlterModelTable(
            name='bogiechecksheet',
            table='bogie_checksheets',
        ),
        migrations.AlterModelTable(
            name='wheelspecification',
            table='wheel_specifications',
        ),
    ]
