# Generated by Django 5.2.4 on 2025-08-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_bogiechecksheet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bogiechecksheet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bogie Checksheet'},
        ),
        migrations.AlterModelOptions(
            name='wheelspecification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Wheel Specification'},
        ),
        migrations.AlterField(
            model_name='bogiechecksheet',
            name='form_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wheelspecification',
            name='form_number',
            field=models.CharField(help_text='Unique form identifier', max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='bogiechecksheet',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wheelspecification',
            table=None,
        ),
    ]
